services:
  marreta:
    container_name: marreta
    build: https://github.com/andrema2/marreta.git#main
    volumes:
      - /dockers/marreta/cache:/app/cache
      - /dockers/marreta/logs:/app/logs
    environment:
      - SITE_NAME=${SITE_NAME:-Marreta}
      - SITE_DESCRIPTION=${SITE_DESCRIPTION:-Leitor sem barreiras}
      - SITE_URL=${SITE_URL:-https://marreta.andremartins.org}
      - DNS_SERVERS=${DNS_SERVERS:-1.1.1.1,8.8.8.8}
      - LANGUAGE=${LANGUAGE:-pt-br}
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
      - SELENIUM_HOST=${SELENIUM_HOST:-selenium-hub:4444}
      - CLEANUP_DAYS=${CLEANUP_DAYS:-7}
      - PROXY_LIST=${PROXY_LIST:-}
    networks:
      - proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.marreta.rule=Host(`marreta.andremartins.org`)
      - traefik.http.routers.marreta.entrypoints=websecure
      - traefik.http.routers.marreta.tls=true
      - traefik.http.services.marreta.loadbalancer.server.port=80
      - traefik.docker.network=proxy
    restart: unless-stopped

  selenium-hub:
    image: selenium/hub:4.27.0-20241204
    container_name: selenium-hub
    environment:
      - SE_ENABLE_TRACING=false
      - GRID_MAX_SESSION=10
      - GRID_BROWSER_TIMEOUT=10
      - GRID_TIMEOUT=10
    depends_on:
      - marreta
    restart: unless-stopped

  selenium-chromium:
    container_name: selenium-chromium
    image: selenium/node-chromium:4.27.0-20241204
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
    depends_on:
      - selenium-hub
    restart: unless-stopped

  selenium-firefox:
    container_name: selenium-firefox
    image: selenium/node-firefox:4.27.0-20241204
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
    depends_on:
      - selenium-hub
    restart: unless-stopped

networks:
  proxy:
    external: true
